---
- import_tasks: base.yml
  tags: [base, packages]

- import_tasks: google.yml
  tags: [google, cloud, kubectl]

- import_tasks: desktop.yml
  tags: [desktop, gnome]

- import_tasks: virtualization.yml
  tags: [virtualbox, virtualization]

- import_tasks: security.yml
  tags: [security, clamav]

- import_tasks: cleanup.yml
  tags: [cleanup]

