---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - apt-transport-https
      - curl
      - dkms
      - ethtool
      - git-all
      - inetutils-traceroute
      - keepassxc
      - linux-generic
      - linux-headers-6.8.0-47-generic
      - net-tools
      - nmap
      - pavucontrol
      - pdfarranger
      - python3-xlib
    state: present

