---
- name: Install ClamAV
  apt:
    name:
      - clamav
      - clamav-daemon
    state: present

- name: Stop clamav-freshclam before initial update
  service:
    name: clamav-freshclam
    state: stopped
  when: clamav_update_on_install

- name: Run freshclam
  command: freshclam
  when: clamav_update_on_install
  notify: restart clamav-daemon

